services:
  s3app:
    image: prawee/strapi
    container_name: 68-s3-app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASS}"
    ports:
      - "${APPLICATION_PORT}:1337"