services:
  s3db:
    extends:
      file: db.yaml
      service: s3db

  pgadmin:
    extends:
      file: admin.yaml
      service: pgadmin
    depends_on:
      - s3db

  s3app:
    extends:
      file: app.yaml
      service: s3app
    depends_on:
      - pgadmin
